import React, { useState } from 'react';
import { useSAP } from '../../context/SAPContext';
import { Wrench, Plus, X, AlertTriangle, Gauge, Truck, Clock, Package, Sparkles } from 'lucide-react';
import { classifyNotificationText } from '../../services/notificationNLPClassifierService';

export const CreateWOModal = ({ isOpen, onClose, initialAssetId }) => {
  const { assets, materials, workOrders, employees, createWorkOrder, addToast } = useSAP();

  const [notes, setNotes] = useState('');
  const [type, setType] = useState('PM01');
  const [priority, setPriority] = useState('Alta');
  const [equipmentId, setEquipmentId] = useState(initialAssetId || assets[0]?.id || '');
  const [costCenter, setCostCenter] = useState('CC-4100');
  const [assignedTech, setAssignedTech] = useState(employees[0]?.name || 'Jorge Silva San Martín');
  const [plannedHours, setPlannedHours] = useState(4.0);
  const [plannedCost, setPlannedCost] = useState(300.00);
  const [selectedPlannedMaterial, setSelectedPlannedMaterial] = useState('');
  const [plannedMaterialQty, setPlannedMaterialQty] = useState(1);

  // Counter Correction States
  const [isCounterCorrection, setIsCounterCorrection] = useState(false);
  const [correctionReason, setCorrectionReason] = useState('');

  // Auto-seleccionar equipo al abrir o cuando cambia assets o initialAssetId
  React.useEffect(() => {
    if (isOpen) {
      if (initialAssetId && assets.some(a => a.id === initialAssetId)) {
        setEquipmentId(initialAssetId);
      } else if (assets.length > 0 && (!equipmentId || !assets.some(a => a.id === equipmentId))) {
        setEquipmentId(assets[0].id);
      }
    }
  }, [isOpen, initialAssetId, assets]);

  // Computed Autogenerated Title (Standard SAP PM Pattern)
  const selectedAsset = (assets || []).find(a =>
    a.id.toLowerCase().trim() === (equipmentId || '').toLowerCase().trim() ||
    a.name.toLowerCase().trim() === (equipmentId || '').toLowerCase().trim() ||
    (a.plate && a.plate.toLowerCase().trim() === (equipmentId || '').toLowerCase().trim())
  );
  const assetName = selectedAsset ? `${selectedAsset.name} (${selectedAsset.plate || selectedAsset.id})` : equipmentId;
  const typeLabel = type === 'PM01' ? 'Mantenimiento Correctivo (PM01)' : type === 'PM02' ? 'Mantenimiento Preventivo (PM02)' : 'Inspección & Calibración (PM03)';
  const computedTitle = notes.trim() ? `${typeLabel} — ${assetName} [${notes.trim()}]` : `${typeLabel} — ${assetName}`;

  // 🚜 Industrial Counters: Hourmeter & Kilometrage for Machinery & Vehicles
  const [hourmeter, setHourmeter] = useState('');
  const [odometer, setOdometer] = useState('');
  const [validationError, setValidationError] = useState('');

  // Find previous maximum counter readings for the selected equipment/vehicle
  const previousWOs = workOrders.filter(w => w.equipmentId === equipmentId);
  const lastRecordedHourmeter = previousWOs.reduce((max, w) => (w.hourmeter && Number(w.hourmeter) > max ? Number(w.hourmeter) : max), selectedAsset?.hourmeter || 0);
  const lastRecordedOdometer = previousWOs.reduce((max, w) => (w.odometer && Number(w.odometer) > max ? Number(w.odometer) : max), selectedAsset?.odometer || 0);

  const correctionCount = Number(selectedAsset?.counterCorrectionCount) || 0;
  const isHourmeterLower = hourmeter && lastRecordedHourmeter > 0 && Number(hourmeter) < lastRecordedHourmeter;
  const isOdometerLower = odometer && lastRecordedOdometer > 0 && Number(odometer) < lastRecordedOdometer;
  const isLowerValueDetected = isHourmeterLower || isOdometerLower;

  // 🔍 Regla de Negocio IW31: Validar existencia del equipo en el Maestro de Activos (IE03)
  const targetAssetExists = (assets || []).some(a => {
    if (!equipmentId) return false;
    const searchStr = equipmentId.toLowerCase().trim();
    const idClean = (a.id || '').toLowerCase().trim();
    const nameClean = (a.name || '').toLowerCase().trim();
    const plateClean = (a.plate || '').toLowerCase().trim();
    return idClean === searchStr || nameClean === searchStr || plateClean === searchStr || idClean.includes(searchStr) || searchStr.includes(idClean);
  });

  // 🔍 Regla de Negocio IW31: Validar existencia del técnico responsable en Maestro de Personal (HCM)
  const assignedTechName = (assignedTech || '').trim();
  const targetTechExists = (employees || []).some(e =>
    e.name.toLowerCase().trim() === assignedTechName.toLowerCase() ||
    e.id.toLowerCase().trim() === assignedTechName.toLowerCase() ||
    assignedTechName.toLowerCase().includes(e.name.toLowerCase().trim()) ||
    e.name.toLowerCase().trim().includes(assignedTechName.toLowerCase())
  );

  // 🔍 Regla de Negocio IW31: Detectar si ya existe una OT activa para el mismo equipo y tipo de orden
  const duplicateActiveWO = workOrders.find(w =>
    w.equipmentId === equipmentId &&
    w.type === type &&
    (w.status === 'CRTE' || w.status === 'REL' || w.status === 'PCNF')
  );

  if (!isOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();
    setValidationError('');

    // ⛔ IW31-E001: El equipo debe existir en la base de datos de Activos (IE03)
    if (!equipmentId || !targetAssetExists) {
      const errorMsg = `[IW31-E001] El equipo "${equipmentId || 'Sin código'}" no existe en IE03.`;
      setValidationError(errorMsg);
      if (addToast) addToast(errorMsg, 'error');
      return;
    }

    // ⛔ IW31-E002: El técnico responsable debe existir en el Maestro de Personal HCM (employees)
    if (!assignedTechName || !targetTechExists) {
      const errorMsg = `[IW31-E002] El técnico "${assignedTechName || 'Sin asignar'}" no existe en HCM.`;
      setValidationError(errorMsg);
      if (addToast) addToast(errorMsg, 'error');
      return;
    }

    // ⛔ IW31-E003: Bloquear duplicación de órdenes activas de las mismas características
    if (duplicateActiveWO) {
      const errorMsg = `[IW31-E003] Ya existe la Orden Activa (${duplicateActiveWO.id} - ${duplicateActiveWO.status}) para ${equipmentId}.`;
      setValidationError(errorMsg);
      if (addToast) addToast(errorMsg, 'error');
      return;
    }

    const newHourmeter = hourmeter ? Number(hourmeter) : null;
    const newOdometer = odometer ? Number(odometer) : null;

    // ⛔ IW31-E004: Lectura de contador menor a registro previo
    if (isLowerValueDetected && !isCounterCorrection) {
      const errorMsg = `[IW31-E004] Lectura de contador menor al registro previo. Active "Autorizar Corrección".`;
      setValidationError(errorMsg);
      if (addToast) addToast(errorMsg, 'error');
      return;
    }

    // ⛔ IW31-E005: La reserva inicial de repuestos MM es obligatoria
    if (!selectedPlannedMaterial) {
      const errorMsg = `[IW31-E005] Debe seleccionar un repuesto MM obligatoriamente para pre-reservar inventario.`;
      setValidationError(errorMsg);
      if (addToast) addToast(errorMsg, 'error');
      return;
    }

    const plannedComponents = [];
    if (selectedPlannedMaterial) {
      const matObj = materials.find(m => m.id === selectedPlannedMaterial);
      if (matObj) {
        plannedComponents.push({
          materialId: matObj.id,
          description: matObj.name,
          qtyPlanned: Number(plannedMaterialQty || 1),
          qtyIssued: 0,
          unit: matObj.unit,
          unitPrice: matObj.unitPrice
        });
      }
    }

    const success = createWorkOrder({
      title: computedTitle,
      type,
      priority,
      equipmentId,
      costCenter,
      assignedTech,
      plannedHours: Number(plannedHours),
      plannedCost: Number(plannedCost),
      hourmeter: newHourmeter,
      odometer: newOdometer,
      isCounterCorrection,
      correctionReason,
      components: plannedComponents,
      plannedComponents: plannedComponents,
      plannedMaterialId: selectedPlannedMaterial,
      startDate: new Date().toISOString().split('T')[0],
      targetFinishDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
      plannerGroup: 'GRP-MAINT',
      settlementAccount: 'CTR-COSTO-GENERAL'
    });

    if (success !== false) {
      setNotes('');
      setIsCounterCorrection(false);
      setCorrectionReason('');
      setValidationError('');
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-100 dark:bg-slate-950 text-slate-900 dark:text-white overflow-y-auto flex flex-col animate-in fade-in duration-200">
      {/* Sticky Top Fiori Navigation Header */}
      <div className="sticky top-0 z-30 bg-slate-900 text-white px-6 py-3.5 border-b border-slate-800 flex items-center justify-between shadow-2xl shrink-0">
        <div className="flex items-center space-x-4">
          <button
            onClick={onClose}
            type="button"
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-xs font-bold border border-slate-700 cursor-pointer"
          >
            <X className="w-4 h-4" />
            <span>Cerrar</span>
          </button>
          <div>
            <div className="flex items-center space-x-2 text-[11px] text-slate-400 font-mono">
              <span>Mantenimiento</span>
              <span>/</span>
              <span>Órdenes de Trabajo</span>
              <span>/</span>
              <span className="text-amber-400 font-bold">#mnt-ordenes</span>
            </div>
            <h2 className="text-base font-black text-white flex items-center gap-2 mt-0.5">
              <Wrench className="w-4 h-4 text-amber-400" />
              <span>Crear Orden de Trabajo de Mantenimiento (nebex:mantenimiento:ordenes)</span>
            </h2>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-bold text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            Cancelar
          </button>
          <button
            type="submit"
            form="iw31-form"
            disabled={!selectedPlannedMaterial || !!duplicateActiveWO || !targetAssetExists || !targetTechExists || !equipmentId || !assignedTechName || (isLowerValueDetected && !isCounterCorrection)}
            className={`px-5 py-2 rounded-xl text-xs font-black transition-all flex items-center gap-2 shadow-lg ${
              (!selectedPlannedMaterial || duplicateActiveWO || !targetAssetExists || !targetTechExists || !equipmentId || !assignedTechName || (isLowerValueDetected && !isCounterCorrection))
                ? 'bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-700'
                : 'bg-amber-500 hover:bg-amber-600 text-slate-950 shadow-amber-500/20 cursor-pointer'
            }`}
          >
            <Plus className="w-4 h-4" />
            <span>
              {!targetAssetExists
                ? 'ERR: NEBEX-001 (Equipo Inexistente)'
                : !targetTechExists
                ? 'ERR: NEBEX-002 (Técnico Inexistente)'
                : duplicateActiveWO
                ? 'ERR: NEBEX-003 (Orden Duplicada)'
                : isLowerValueDetected && !isCounterCorrection
                ? 'ERR: NEBEX-004 (Lectura Menor)'
                : !selectedPlannedMaterial
                ? 'ERR: NEBEX-005 (Seleccione Repuesto)'
                : 'Guardar y Contabilizar Orden (#mnt-ordenes)'}
            </span>
          </button>
        </div>
      </div>

      {/* Main Canvas Workspace */}
      <div className="flex-1 max-w-7xl w-full mx-auto p-6 space-y-6">
        <form id="iw31-form" onSubmit={handleSubmit} className="space-y-6 text-xs">
          {/* 🚫 Banners de Error Ultra-Compactos (Micro Badges Estándar NEBEX) */}
          {(!equipmentId || !targetAssetExists) && (
            <div className="bg-rose-500/10 border border-rose-500/30 px-3 py-1.5 rounded-lg text-rose-600 dark:text-rose-400 text-[11px] flex items-center space-x-2 font-mono font-bold animate-in fade-in">
              <AlertTriangle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
              <span>ERR: NEBEX-001 — Equipo "{equipmentId || 'Sin código'}" no existe en Activos (#flota-activos)</span>
            </div>
          )}

          {(!assignedTechName || !targetTechExists) && (
            <div className="bg-rose-500/10 border border-rose-500/30 px-3 py-1.5 rounded-lg text-rose-600 dark:text-rose-400 text-[11px] flex items-center space-x-2 font-mono font-bold animate-in fade-in">
              <AlertTriangle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
              <span>ERR: NEBEX-002 — Técnico "{assignedTechName || 'Sin asignar'}" no existe en HCM</span>
            </div>
          )}

          {duplicateActiveWO && (
            <div className="bg-rose-500/10 border border-rose-500/30 px-3 py-1.5 rounded-lg text-rose-600 dark:text-rose-400 text-[11px] flex items-center space-x-2 font-mono font-bold animate-in fade-in">
              <AlertTriangle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
              <span>ERR: NEBEX-003 — Orden activa duplicada ({duplicateActiveWO.id})</span>
            </div>
          )}

          {isLowerValueDetected && !isCounterCorrection && (
            <div className="bg-amber-500/10 border border-amber-500/30 px-3 py-1.5 rounded-lg text-amber-600 dark:text-amber-400 text-[11px] flex items-center space-x-2 font-mono font-bold animate-in fade-in">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-500 shrink-0" />
              <span>ERR: NEBEX-004 — Contador menor al previo (Marque "Autorizar Corrección")</span>
            </div>
          )}

          {!selectedPlannedMaterial && (
            <div className="bg-rose-500/10 border border-rose-500/30 px-3 py-1.5 rounded-lg text-rose-600 dark:text-rose-400 text-[11px] flex items-center space-x-2 font-mono font-bold animate-in fade-in">
              <AlertTriangle className="w-3.5 h-3.5 text-rose-500 shrink-0" />
              <span>ERR: NEBEX-005 — Reserva de Repuesto Obligatoria (Seleccione un componente)</span>
            </div>
          )}

          {/* 3-Column Structured Layout */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Column 1: Datos Generales de la Orden */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl">
              <div className="flex items-center space-x-2 border-b border-slate-200 dark:border-slate-800 pb-3 text-amber-600 dark:text-amber-400 font-bold text-xs">
                <Wrench className="w-4 h-4" />
                <span>1. Parámetros Generales de la Orden</span>
              </div>

              <div className="space-y-3">
                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Tipo de Orden ERP</label>
                  <select
                    value={type}
                    onChange={(e) => setType(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-bold focus:ring-2 focus:ring-amber-500"
                  >
                    <option value="PM01">PM01 - Mantenimiento Correctivo</option>
                    <option value="PM02">PM02 - Mantenimiento Preventivo</option>
                    <option value="PM03">PM03 - Inspección y Calibración</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Prioridad de Ejecución</label>
                  <select
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-bold focus:ring-2 focus:ring-amber-500"
                  >
                    <option value="Muy Alta">Muy Alta / Urgente</option>
                    <option value="Alta">Alta</option>
                    <option value="Media">Media</option>
                    <option value="Baja">Baja</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Equipo / Maquinaria / Vehículo</label>
                  <select
                    value={equipmentId}
                    onChange={(e) => setEquipmentId(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 focus:ring-2 focus:ring-amber-500 font-bold"
                  >
                    {assets.map(a => (
                      <option key={a.id} value={a.id}>{a.id} - {a.name} ({a.plate || 'Sin Patente'})</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Centro de Coste (CO)</label>
                  <select
                    value={costCenter}
                    onChange={(e) => setCostCenter(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 focus:ring-2 focus:ring-amber-500"
                  >
                    <option value="CC-4100">CC-4100 - Flota & Transportes</option>
                    <option value="CC-1020">CC-1020 - Planta Concentradora</option>
                    <option value="CC-3050">CC-3050 - Mantenimiento Mecánico</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Técnico / Responsable Asignado</label>
                  <select
                    value={assignedTech}
                    onChange={(e) => setAssignedTech(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-bold focus:ring-2 focus:ring-amber-500"
                  >
                    {employees.map(e => (
                      <option key={e.id} value={e.name}>
                        {e.name} — {e.position} ({e.id})
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </div>

            {/* Column 2: Objeto Técnico y Contadores de Flota */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl">
              <div className="flex items-center space-x-2 border-b border-slate-200 dark:border-slate-800 pb-3 text-sky-600 dark:text-sky-400 font-bold text-xs">
                <Gauge className="w-4 h-4" />
                <span>2. Objeto Técnico & Registro de Contadores</span>
              </div>

              <div className="space-y-3">
                <div className="bg-slate-50 dark:bg-slate-950 p-3 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
                  <span className="text-[10px] text-slate-500 dark:text-slate-400 font-mono block">Equipo Seleccionado</span>
                  <div className="font-extrabold text-slate-900 dark:text-white text-xs">{selectedAsset?.name || equipmentId}</div>
                  <div className="text-[10px] text-slate-600 dark:text-slate-400 flex items-center gap-2 mt-1">
                    <span>Ubicación: <strong>{selectedAsset?.location || 'Mina Norte'}</strong></span>
                    <span>•</span>
                    <span>Patente: <strong>{selectedAsset?.plate || 'Sin Patente'}</strong></span>
                  </div>
                </div>

                {/* Counter inputs */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1 flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-sky-600" /> Horómetro
                    </label>
                    <input
                      type="number"
                      placeholder={`Último: ${lastRecordedHourmeter} hrs`}
                      value={hourmeter}
                      onChange={(e) => setHourmeter(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-mono font-bold"
                    />
                    <span className="text-[10px] text-slate-500 dark:text-slate-400 block mt-1">
                      Anterior: <strong className="font-mono text-slate-700 dark:text-slate-300">{lastRecordedHourmeter}</strong> hrs
                    </span>
                  </div>

                  <div>
                    <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1 flex items-center gap-1">
                      <Truck className="w-3.5 h-3.5 text-emerald-600" /> Kilometraje
                    </label>
                    <input
                      type="number"
                      placeholder={`Último: ${lastRecordedOdometer} km`}
                      value={odometer}
                      onChange={(e) => setOdometer(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-mono font-bold"
                    />
                    <span className="text-[10px] text-slate-500 dark:text-slate-400 block mt-1">
                      Anterior: <strong className="font-mono text-slate-700 dark:text-slate-300">{lastRecordedOdometer}</strong> km
                    </span>
                  </div>
                </div>

                {/* Counter Warning / Correction Block */}
                {isLowerValueDetected && (
                  <div className="bg-amber-50 border border-amber-200 dark:bg-amber-950/70 dark:border-amber-700 p-3 rounded-xl space-y-2 text-amber-900 dark:text-amber-200">
                    <div className="flex items-center space-x-1.5 text-amber-800 dark:text-amber-300 font-bold">
                      <AlertTriangle className="w-4 h-4 shrink-0" />
                      <span>Lectura Infeior Detectada</span>
                    </div>
                    <p className="text-[11px] leading-relaxed">
                      El valor ingresado es menor a la última lectura contabilizada. Active la casilla de autorización excepcional si se trata de un ajuste de contador.
                    </p>
                    <label className="flex items-center space-x-2 pt-1 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={isCounterCorrection}
                        onChange={(e) => setIsCounterCorrection(e.target.checked)}
                        className="rounded border-amber-400 text-amber-600 focus:ring-amber-500"
                      />
                      <span className="font-bold text-xs text-amber-900 dark:text-amber-200">Autorizar Corrección Excepcional</span>
                    </label>

                    {isCounterCorrection && (
                      <input
                        type="text"
                        required
                        placeholder="Ingrese motivo del ajuste (ej: Cambio de tablero o horómetro)..."
                        value={correctionReason}
                        onChange={(e) => setCorrectionReason(e.target.value)}
                        className="w-full bg-white dark:bg-slate-900 border border-amber-300 dark:border-amber-600 rounded-lg p-2 text-xs text-slate-900 dark:text-white"
                      />
                    )}
                  </div>
                )}

                <div>
                  <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Descripción Breve / Síntoma de Falla</label>
                  <textarea
                    rows="3"
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="Ej. Ruido anómalo en bomba hidráulica principal / Fuga de aceite por retén..."
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 focus:bg-white"
                  />

                  {/* Realtime NLP Machine Learning Auto-Classifier */}
                  {notes.trim().length > 3 && (() => {
                    const nlp = classifyNotificationText(notes);
                    return (
                      <div className="mt-2 p-3 rounded-xl bg-purple-950/90 border border-purple-700/60 text-purple-100 text-xs space-y-1.5 animate-in fade-in shadow-md">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-amber-300 flex items-center gap-1.5">
                            <Sparkles className="w-3.5 h-3.5 text-amber-300 animate-spin" />
                            <span>Auto-Clasificación NLP (Machine Learning Engine)</span>
                          </span>
                          <span className="text-[10px] font-mono text-purple-300 bg-purple-900 px-2 py-0.5 rounded border border-purple-700">
                            Confianza: {nlp.confidenceScore}%
                          </span>
                        </div>
                        <div className="flex flex-wrap items-center justify-between gap-2 text-[11px] pt-0.5">
                          <div>
                            Prioridad Sugerida: <strong className="text-amber-300 font-bold">{nlp.suggestedPriority}</strong> • Componente: <strong className="text-white font-bold">{nlp.suggestedComponent}</strong>
                          </div>
                          {priority !== nlp.suggestedPriority && (
                            <button
                              type="button"
                              onClick={() => setPriority(nlp.suggestedPriority)}
                              className="bg-purple-600 hover:bg-purple-500 text-white text-[10px] font-bold px-2 py-1 rounded-lg transition-all cursor-pointer shadow-xs border border-purple-400/50"
                            >
                              Aplicar Prioridad {nlp.suggestedPriority}
                            </button>
                          )}
                        </div>
                      </div>
                    );
                  })()}
                </div>
              </div>
            </div>

            {/* Column 3: Planificación de Tiempos, Costos & Repuestos MM */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl">
              <div className="flex items-center space-x-2 border-b border-slate-200 dark:border-slate-800 pb-3 text-emerald-600 dark:text-emerald-400 font-bold text-xs">
                <Package className="w-4 h-4" />
                <span>3. Tiempos, Costos & Componentes Reservados MM</span>
              </div>

              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Horas Planificadas</label>
                    <input
                      type="number"
                      step="0.5"
                      value={plannedHours}
                      onChange={(e) => setPlannedHours(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-mono font-bold"
                    />
                  </div>

                  <div>
                    <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">Costo Planificado ($)</label>
                    <input
                      type="number"
                      step="10"
                      value={plannedCost}
                      onChange={(e) => setPlannedCost(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-mono font-bold"
                    />
                  </div>
                </div>

                <div className="pt-2 border-t border-slate-200 dark:border-slate-800 space-y-2">
                  <label className="block text-slate-700 dark:text-slate-300 font-bold flex items-center justify-between">
                    <span>Reserva Inicial de Repuesto MM <strong className="text-amber-500 font-bold">(Obligatorio)</strong></span>
                    <span className="text-[10px] text-rose-500 font-mono">* IW31-E005</span>
                  </label>
                  <select
                    required
                    value={selectedPlannedMaterial}
                    onChange={(e) => setSelectedPlannedMaterial(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2.5 rounded-xl border border-slate-300 dark:border-slate-700 font-bold focus:ring-2 focus:ring-amber-500"
                  >
                    <option value="">-- Seleccionar Repuesto MM Obligatorio --</option>
                    {materials.map(m => (
                      <option key={m.id} value={m.id}>
                        {m.id} - {m.name} (Stock: {m.stock} {m.unit})
                      </option>
                    ))}
                  </select>

                  {selectedPlannedMaterial && (
                    <div className="flex items-center space-x-3 pt-1">
                      <div className="flex-1">
                        <label className="block text-slate-500 text-[10px] font-bold mb-1">Cantidad a Reservar</label>
                        <input
                          type="number"
                          min="1"
                          value={plannedMaterialQty}
                          onChange={(e) => setPlannedMaterialQty(e.target.value)}
                          className="w-full bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 p-2 rounded-lg border border-slate-300 dark:border-slate-700 font-mono font-bold"
                        />
                      </div>
                      <div className="text-right text-[11px] font-mono text-slate-600 dark:text-slate-400 pt-3">
                        Subtotal: <strong>${((materials.find(m => m.id === selectedPlannedMaterial)?.unitPrice || 0) * Number(plannedMaterialQty)).toLocaleString()}</strong>
                      </div>
                    </div>
                  )}
                </div>

                {validationError && (
                  <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-rose-700 text-[11px] font-bold leading-relaxed">
                    {validationError}
                  </div>
                )}
              </div>
            </div>
          </div>
        </form>
      </div>

      {/* Sticky Bottom Action Summary Bar */}
      <div className="sticky bottom-0 z-30 bg-slate-900 text-white px-6 py-3.5 border-t border-slate-800 flex items-center justify-between shrink-0 no-print">
        <div className="flex items-center space-x-6 text-xs">
          <div>
            <span className="text-slate-400 block text-[10px]">Título Generado Orden</span>
            <span className="font-bold text-white text-sm truncate max-w-md block">{computedTitle}</span>
          </div>
          <div>
            <span className="text-slate-400 block text-[10px]">Costo Estimado Planificado</span>
            <span className="font-mono font-bold text-emerald-400 text-sm">${Number(plannedCost).toLocaleString()} CLP</span>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-bold text-slate-400 hover:text-white"
          >
            Cancelar
          </button>
          <button
            type="submit"
            form="iw31-form"
            disabled={!!duplicateActiveWO}
            className={`px-5 py-2 rounded-xl text-xs font-black transition-all flex items-center gap-2 shadow-lg ${
              duplicateActiveWO
                ? 'bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-700'
                : 'bg-amber-500 hover:bg-amber-600 text-slate-950 shadow-amber-500/20 cursor-pointer'
            }`}
          >
            <Plus className="w-4 h-4" />
            <span>{duplicateActiveWO ? 'Bloqueado por Duplicidad' : 'Guardar y Contabilizar Orden (#mnt-ordenes)'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
